#!/usr/bin/env bash
#
# azure-setup.sh — provision / tear down Azure resources for the
# Student Study Helper midterm project (INTP302).
#
# Usage:
#   ./azure-setup.sh up      # create all resources + print env vars
#   ./azure-setup.sh info    # print endpoints/keys for an existing stack
#   ./azure-setup.sh down    # delete the resource group (everything)
#
# Prereqs: Azure CLI installed and logged in (`az login`).
# Cost note: defaults use cheap/free tiers. ALWAYS run `down` after grading.

set -euo pipefail

# ----------------------------------------------------------------------
# CONFIG — edit these
# ----------------------------------------------------------------------
PROJECT="studyhelper"                 # short name, lowercase, no spaces
LOCATION="canadacentral"              # az account list-locations -o table
RG="rg-${PROJECT}"                    # resource group name

# Global-unique names need a stable suffix. Generated once and cached so
# `up`, `info`, and `down` all agree on the same names.
SUFFIX_FILE=".azure-suffix"
if [[ -f "$SUFFIX_FILE" ]]; then
  SUFFIX="$(cat "$SUFFIX_FILE")"
else
  SUFFIX="$(tr -dc 'a-z0-9' </dev/urandom | head -c5 || true)"
  echo "$SUFFIX" > "$SUFFIX_FILE"
fi

STORAGE="st${PROJECT}${SUFFIX}"       # 3-24 chars, lowercase+digits only
AI_NAME="ai-${PROJECT}-${SUFFIX}"     # Azure AI Language (Cognitive Services)
PLAN="plan-${PROJECT}"                # App Service plan
WEBAPP="app-${PROJECT}-${SUFFIX}"     # Web App (public URL host)

# Tiers (swap up for more power if needed):
STORAGE_SKU="Standard_LRS"
AI_SKU="F0"                           # F0 = free tier for Language; use S for more
PLAN_SKU="B1"                         # F1 = free (limited); B1 = basic, reliable
NODE_RUNTIME="NODE:24-lts"            # verify: az webapp list-runtimes -o table | grep NODE

ENV_FILE=".env.local"                 # local dev env file (Next.js convention)

# ----------------------------------------------------------------------
# helpers
# ----------------------------------------------------------------------
require_login() {
  if ! az account show >/dev/null 2>&1; then
    echo "Not logged in. Run: az login" >&2
    exit 1
  fi
  echo ">> Using subscription: $(az account show --query name -o tsv)"
}

# Write secrets to the local env file in a consistent, ready-to-run pattern.
# Args: $1=storage conn, $2=AI key, $3=AI endpoint
write_env() {
  local conn="$1" key="$2" endpoint="$3"

  if [[ -f "$ENV_FILE" ]]; then
    cp "$ENV_FILE" "${ENV_FILE}.bak"
    echo ">> Existing $ENV_FILE backed up to ${ENV_FILE}.bak"
  fi

  cat > "$ENV_FILE" <<EOF
# Generated by azure-setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT. Ensure $ENV_FILE is listed in .gitignore.

# --- Azure Storage ---
AZURE_STORAGE_CONNECTION_STRING="$conn"

# --- Azure AI Language ---
AZURE_LANGUAGE_KEY="$key"
AZURE_LANGUAGE_ENDPOINT="$endpoint"

# --- App ---
AZURE_WEBAPP_URL="https://${WEBAPP}.azurewebsites.net"
EOF

  chmod 600 "$ENV_FILE"   # restrict to owner; secrets shouldn't be world-readable
  echo ">> Wrote secrets to $ENV_FILE (chmod 600)"

  # Best-effort guard: make sure the env file can't be committed.
  if [[ -d .git || -f .gitignore ]]; then
    local added=()
    for entry in "$ENV_FILE" "${ENV_FILE}.bak" "$SUFFIX_FILE"; do
      if ! grep -qxF "$entry" .gitignore 2>/dev/null; then
        echo "$entry" >> .gitignore
        added+=("$entry")
      fi
    done
    [[ ${#added[@]} -gt 0 ]] && echo ">> Added to .gitignore: ${added[*]}"
  fi
}

# ----------------------------------------------------------------------
# up — create everything
# ----------------------------------------------------------------------
up() {
  require_login

  if az group exists --name "$RG" | grep -q true; then
    echo ">> Resource group already exists: $RG (reusing)"
  else
    echo ">> Creating resource group: $RG ($LOCATION)"
    az group create --name "$RG" --location "$LOCATION" -o none
  fi

  if az storage account show --name "$STORAGE" --resource-group "$RG" -o none 2>/dev/null; then
    echo ">> Storage account already exists: $STORAGE (reusing)"
  else
    echo ">> Creating storage account: $STORAGE"
    az storage account create \
      --name "$STORAGE" --resource-group "$RG" --location "$LOCATION" \
      --sku "$STORAGE_SKU" --kind StorageV2 -o none
  fi

  if az cognitiveservices account show --name "$AI_NAME" --resource-group "$RG" -o none 2>/dev/null; then
    echo ">> Azure AI Language resource already exists: $AI_NAME (reusing)"
  elif az cognitiveservices account list-deleted \
         --query "[?name=='${AI_NAME}']" -o tsv 2>/dev/null | grep -q .; then
    echo ">> Soft-deleted Cognitive Services account found: $AI_NAME"
    echo "   (r) Restore it  — recover the existing account and its data"
    echo "   (p) Purge + new — permanently delete it and provision a fresh one"
    read -rp "   Choice [r/p]: " cs_choice
    case "${cs_choice,,}" in
      p)
        echo ">> Purging $AI_NAME..."
        az cognitiveservices account purge \
          --name "$AI_NAME" --resource-group "$RG" --location "$LOCATION"
        echo ">> Creating new Azure AI Language resource: $AI_NAME"
        az cognitiveservices account create \
          --name "$AI_NAME" --resource-group "$RG" --location "$LOCATION" \
          --kind TextAnalytics --sku "$AI_SKU" --yes -o none
        ;;
      *)
        echo ">> Restoring $AI_NAME..."
        az cognitiveservices account recover \
          --name "$AI_NAME" --resource-group "$RG" --location "$LOCATION" -o none
        echo ">> Restored."
        ;;
    esac
  else
    echo ">> Creating Azure AI Language resource: $AI_NAME"
    az cognitiveservices account create \
      --name "$AI_NAME" --resource-group "$RG" --location "$LOCATION" \
      --kind TextAnalytics --sku "$AI_SKU" --yes -o none
  fi

  # --- Alternative: Azure OpenAI instead of AI Language ---------------
  # az cognitiveservices account create \
  #   --name "$AI_NAME" --resource-group "$RG" --location "$LOCATION" \
  #   --kind OpenAI --sku S0 --yes -o none
  # (then deploy a model with: az cognitiveservices account deployment create ...)
  # --------------------------------------------------------------------

  if az appservice plan show --name "$PLAN" --resource-group "$RG" -o none 2>/dev/null; then
    echo ">> App Service plan already exists: $PLAN (reusing)"
  else
    echo ">> Creating App Service plan: $PLAN ($PLAN_SKU, Linux)"
    az appservice plan create \
      --name "$PLAN" --resource-group "$RG" \
      --sku "$PLAN_SKU" --is-linux -o none
  fi

  if az webapp show --name "$WEBAPP" --resource-group "$RG" -o none 2>/dev/null; then
    echo ">> Web App already exists: $WEBAPP (reusing)"
  else
    echo ">> Creating Web App: $WEBAPP"
    az webapp create \
      --name "$WEBAPP" --resource-group "$RG" \
      --plan "$PLAN" --runtime "$NODE_RUNTIME" -o none
  fi

  echo ">> Pushing secrets into App Settings (server-side, never in repo)"
  local conn key endpoint
  conn="$(az storage account show-connection-string \
    --name "$STORAGE" --resource-group "$RG" --query connectionString -o tsv)"
  key="$(az cognitiveservices account keys list \
    --name "$AI_NAME" --resource-group "$RG" --query key1 -o tsv)"
  endpoint="$(az cognitiveservices account show \
    --name "$AI_NAME" --resource-group "$RG" --query properties.endpoint -o tsv)"

  az webapp config appsettings set --name "$WEBAPP" --resource-group "$RG" \
    --settings \
      AZURE_STORAGE_CONNECTION_STRING="$conn" \
      AZURE_LANGUAGE_KEY="$key" \
      AZURE_LANGUAGE_ENDPOINT="$endpoint" \
    -o none

  echo ">> Writing local env file"
  write_env "$conn" "$key" "$endpoint"

  echo ""
  echo "=================================================================="
  echo " DONE. Live app URL: https://${WEBAPP}.azurewebsites.net"
  echo "=================================================================="
  echo " Secrets written to $ENV_FILE. To run locally:"
  echo "     npm install && npm run dev"
  echo "=================================================================="
}

# ----------------------------------------------------------------------
# info — reprint endpoints/keys for an existing stack
# ----------------------------------------------------------------------
info() {
  require_login
  local conn key endpoint
  endpoint="$(az cognitiveservices account show \
      --name "$AI_NAME" --resource-group "$RG" --query properties.endpoint -o tsv)"
  key="$(az cognitiveservices account keys list \
      --name "$AI_NAME" --resource-group "$RG" --query key1 -o tsv)"
  conn="$(az storage account show-connection-string \
      --name "$STORAGE" --resource-group "$RG" --query connectionString -o tsv)"

  echo "Resource group : $RG"
  echo "App URL        : https://${WEBAPP}.azurewebsites.net"
  echo "Storage acct   : $STORAGE"
  echo "AI endpoint    : $endpoint"
  echo "AI key1        : $key"
  echo "Storage conn   : $conn"

  # Regenerate the local env file so teammates can pull secrets for an
  # already-provisioned stack (clone repo -> ./azure-setup.sh info -> run).
  write_env "$conn" "$key" "$endpoint"

  echo ">> Syncing secrets to App Settings (idempotent)"
  az webapp config appsettings set --name "$WEBAPP" --resource-group "$RG" \
    --settings \
      AZURE_STORAGE_CONNECTION_STRING="$conn" \
      AZURE_LANGUAGE_KEY="$key" \
      AZURE_LANGUAGE_ENDPOINT="$endpoint" \
    -o none
}

# ----------------------------------------------------------------------
# down — delete everything (the whole resource group) and purge soft-deleted
#        resources so names are immediately available again.
#
# Flags:
#   --wait   kick off async delete, then poll until the group is gone and
#            purge the soft-deleted Cognitive Services account automatically.
# ----------------------------------------------------------------------
down() {
  local nowait="--no-wait"
  [[ "${1:-}" == "--wait" ]] && nowait=""

  require_login

  if ! az group exists --name "$RG" | grep -q true; then
    echo ">> Resource group '$RG' does not exist — nothing to delete."
  else
    echo ">> Deleting resource group '$RG' and ALL its resources..."
    az group delete --name "$RG" --yes $nowait
    echo ">> Resource group deleted."
  fi

  # Cognitive Services uses soft-delete; the name is held 48 h unless purged.
  # Without --wait the group delete may still be in flight, so the soft-deleted
  # account may not appear yet — re-run with --wait to purge automatically.
  echo ">> Checking for soft-deleted Cognitive Services account '$AI_NAME'..."
  if az cognitiveservices account list-deleted \
       --query "[?name=='${AI_NAME}']" -o tsv 2>/dev/null | grep -q .; then
    az cognitiveservices account purge \
      --name "$AI_NAME" --resource-group "$RG" --location "$LOCATION"
    echo ">> Purged."
  else
    echo ">> No soft-deleted account found — skipping purge."
  fi

  rm -f "$SUFFIX_FILE" "$ENV_FILE" "${ENV_FILE}.bak"
  echo ">> Removed local files: $SUFFIX_FILE, $ENV_FILE"
  echo ">> Done."
}

# ----------------------------------------------------------------------
case "${1:-}" in
  up)   up ;;
  down) down "${2:-}" ;;
  info) info ;;
  *)    echo "Usage: $0 {up|down [--wait]|info}"; exit 1 ;;
esac